---
title: "assignment"
output: html_document
date: "2026-03-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
BiocManager::install("PWMEnrich")
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(GenomicRanges)
  library(ggplot2)
  library(motifmatchr) 
  library(Biostrings)
  library(MotifDb)
  library(universalmotif) 
  library(PWMEnrich) 
  library(GenomeInfoDb)
})
```


# Downlaoding peak sequences for mouse myocytes REST
```{r}
download.file("https://www.encodeproject.org/files/ENCFF368VWJ/@@download/ENCFF368VWJ.bed.gz", "myocyte_REST_ENCFF368VWJ.bed.gz")
peaks <- rtracklayer::import("myocyte_REST_ENCFF368VWJ.bed.gz", format="NarrowPeak")
```
#Loading genome sequence
```{r}
ah <- AnnotationHub()
genome <- ah[["AH68356"]]
genome_seqs <- import(genome)
```

#Factor motifs 
```{r}
motifs <- query(MotifDb, c("REST"))
names(motifs)
motif <- motifs[["Mmusculus-HOCOMOCOv10-REST_MOUSE.H10MO.A"]]
motif 
```

#scan peaks for motifs
```{r}
Biostrings::writeXStringSet(genome_seqs, "genome.fa")
motif2 <- convert_motifs(motif, class="TFBSTools-PWMatrix")
seqlevelsStyle(peaks) <- "Ensembl"
moi <- motifmatchr::matchMotifs(motif2, subject=peaks, genome=Rsamtools::FaFile("genome.fa"),
                                out="positions") 
moi <- moi[[1]]
head(moi)
hist(moi$score)
```
#Proportion of peaks containing motif
```{r}
n_peaks <- length(peaks)
n_peaks_with <- sum((overlapsAny(peaks, moi)))
prop_peaks_with <- n_peaks_with/n_peaks*100
cat("Of the",n_peaks, "peaks", n_peaks_with, "(",round(prop_peaks_with,2),"%)", "contain a motif.")
```

#motifs across genome
```{r}
motif_across_genome <- matchMotifs(motif2, subject=genome_seqs, out="positions")[[1]]
names(motif_across_genome) <- names(genome_seqs)
motif_across_genome <- as(motif_across_genome, "GRanges")
head(motif_across_genome)
```
#proportion genome motifs overlap peak
```{r}
motif_bound <- overlapsAny(motif_across_genome, peaks)
n_motifs <- length(motif_across_genome)
n_motifs_in_peaks <- sum(motif_bound)
prop_motifs_in_peaks <- n_motifs_in_peaks/n_motifs * 100
cat("Of the",n_motifs, "motif instances", n_motifs_in_peaks, "(",round(prop_motifs_in_peaks,2),"%)", "overlap a peak.")
```

